Further dev on check-examples

diff --git a/docs/check-examples b/docs/check-examples
--- a/docs/check-examples
+++ b/docs/check-examples
@@ -1,72 +1,196 @@
 #! /usr/bin/env bash
 
+## This file accepts a couple options (before any files)
+## and then iterates over the remaining command-line arguments as files.
+## The options are
+##    -d <name>  -- here <name> is a default command (see below)
+##    -l <lang>  -- <lang> is the name of a language to use as default
+##                   (a language name as used with ```, e.g.,
+##                   dafny, java, text, cli, ...)
+##    -x <int>   -- <int> is an (non-negative) integer literal giving 
+##                  a default exit code
+## It expects a file to be in github markdown format.
+##
+## It extracts each block of text that is between lines bounded by a pair
+## of lines beginning with ```. The opening ``` is typically follwed
+## immediately (without whitespace) by a language identifier. If no
+## language identifier is present, the default language specified by the -l
+## option is used; if there is no such option, an error is output.
+## The extracted text is placed in a temporary file.
+##
+## If the text blocks are not in matching pairs of ``` markers or if 
+## markers other than 3 backticks are used, the script will fail -- it is
+## not robust against such non-well-formedness.
+## Also, the backticks must start the line without leading whitespace and 
+## the language identifier must follow without whitespace.
+##
+## Each block of extracted text is tested by applying a command.
+## The command is stated by including in the ```dafny line the string
+## <!-- command --> where in that HTML comment string, the 'command' is one
+## of the commands below. If there is no such HTML comment, then the default
+## command given by an option is used; if there is no such option, an error
+## message is issued.
+##
+## Commands (here $F is the name of a file containing the dafny source code
+## under test):
+##   %no-check : do nothing
+##   %check-ok <expect> : runs the command 
+##              "dafny verify -useBaseNameForFilename $F" and checks 
+##              (1) that the exit code is 0
+##              (2) if <expect> is non-empty then it names a file whose
+##                  content matches the actrual output of the above command
+##   %check-error
+##   check
+
 dir=$(dirname "${BASH_SOURCE[0]}")
 dafny="$dir/../Scripts/dafny"
 
+defaultCommand=
+defaultExit=
+defaultLang=
+
+while getopts 'd:x:l:' opt; do
+  case "$opt" in
+    "d") defaultCommand="$OPTARG";;
+    "x") defaultExit="$OPTARG";;
+    "l") defaultLang="$OPTARG";;
+  esac
+done
+shift $(($OPTIND - 1))
+
+## Temporary file
 text=text.dfy
+
+## Tracks if there have been any failures
 ANYFAIL=0
+
+## Loop over all remaining comman-line arguments
 for file in $@ ; do
 
+## Whether this file fails
 FAIL=0
+## line number
 n=0
+## if inblock==1 we are in a ```-delimited block
 inblock=0
+
 command= 
 expect= 
+msg=
+checkingErrors=1
+## Read and process each line of the file.  The file is input on stdin 
+## by redirection after the 'done' corresponding to this while-do
 while IFS= read -r line
 do 
   let n++
-  ##echo LINE $n "$line"
-  echo $line | grep -e '```'  > /dev/null
-  if [ $? -eq "0" ]; then
+
+  ## For header lines (check-errors test), extract the error message from
+  ## the header text (everything but the initial ##[ ]* )
+  ( echo "$line" | grep -E -e '[#][#] ' > /dev/null ) \
+   && msg=`echo "$line" | sed -E -e 's/^##[ ]*//' -e 's/_[a-z]+_/.*/g'`
+
+  ## Check for the marker
+  echo $line | grep -e '```' > /dev/null
+  if [ "$?" == "0" ]; then
     ##echo FOUND BACKTICKS IN $n "$line"
-    if [ $inblock -eq "0" ]; then
+    if [ "$inblock" == "0" ]; then
+      ## get language
+      lang=`echo "$line" | sed -e 's/\`\`\`//' -e 's/[ ].*$//'`
+      if [ -z "$lang" ]; then
+        lang=$defaultLang
+        if [ -z "$lang" ]; then
+          echo NO LANGUAGE LABEL $n "$line"
+          FAIL=1
+        fi
+      fi
+
       command=
-      ( echo "$line" | grep -e '```dafny' > /dev/null ) || echo NO LANGUAGE LABEL $n "$line"
       ( echo "$line" | grep -e '<!--' > /dev/null ) \
           && action=( `echo "$line" | sed -e 's/[^<]*<!--//' -e 's/-->//'` ) \
-          && command=${action[0]} && expect=${action[1]} \
-          || echo NO TEST COMMAND $n "$line"
+          && command=${action[0]} && expect=${action[1]}
+      if [ -z "$command" ]; then
+        command="$defaultCommand"
+        if [ -z "$command" ]; then
+          echo "NO COMMAND GIVEN $n $line"
+          FAIL=1
+        fi
+      fi
+
       inblock=1
       rm -f $text
       touch $text
     else
-      ( echo "$line" | grep -e '```dafny' > /dev/null ) && echo UNEXPECTED LANGUAGE LABEL $n "$line"
+      ## End of backtick block, so check the text
       inblock=0
       ##echo TESTING $command $expect
-      if [ "$command" == "" ]; then
-      echo -n ""
-      elif [ "$command" == "%no-check" ]; then
-         echo -n ""
-      elif [ $command == "%check-ok" ]; then
-        "$dafny" verify $text > actual
-        if [ $? -ne "0" ]; then
-          echo "TEST FAILED" $file line $n  $command $expect
-          cat $text
-          cat actual
+      if [ "$command" == "%no-check" ]; then
+        echo -n ""
+      elif [ "$command" == "%check-ok" ]; then
+        if [ "$lang" != "dafny" ]; then
+          echo EXPECTED A dafny BLOCK, NOT $lang
           FAIL=1
+        else
+          "$dafny" verify -useBaseNameForFileName $text > actual
+          if [ $? -ne "0" ]; then
+            echo "TEST FAILED" $file line $n  $command $expect
+            cat $text
+            cat actual
+            FAIL=1
+          fi
+          if [ -n "$expect" ]; then
+              diff actual $expect
+              if "$?" -ne "0" ]; then
+                  FAIL=1
+                  echo Actual output differs from expected
+                  echo "TEST FAILED" $file line $n  $command $expect
+                  cat $text
+              fi
+          fi
         fi
-        if [ -n "$expect" ]; then
-            diff actual $expect
-            if "$?" -ne "0" ]; then
-                FAIL=1
-                echo Actual output differs from expected
-                echo "TEST FAILED" $file line $n  $command $expect
-                cat $text
+      elif [ "$command" == "%check-cli" ]; then
+        if [ "$lang" != "dafny" ]; then
+          echo EXPECTED A cli BLOCK, NOT $lang
+          FAIL=1
+        else
+          bash $command
+          ec=$?
+          if [ "$ec" != "1" ]; then
+             echo EXPECTED EXIT CODE OF 1, GOT $ec
+             FAIL=1
+          else
+            act=`cat actual`
+	    dif=`echo $act | sed -e "s/$msg//"`
+            if [ -n "$dif" ]; then
+              echo ACTUAL OUTPUT DOES NOT MATCH EXPECTED: "$msg" VS "$act"
+              FAIL=1
             fi
+          fi
         fi
+      elif [ "$command" == "%check-error" ]; then
+        "$dafny" resolve -useBaseNameForFileName $text | head -1 | sed -e 's/[^:]*: //' > actual
+        act=`cat actual`
+	dif=`echo $act | sed -e "s/$msg//"`
+        if [ -n "$dif" ] ; then
+           echo NO MATCH "$msg" VS "$act"
+           FAIL=1
+        fi
+        msg=
+##     elif [ "$command" == "" ]; then
+##        echo -n
       else
          echo UNKNOWN TEST COMMAND $command
+         FAIL=1
       fi
     fi
-  else
-    if [ $inblock -eq "1" ]; then
-      echo "$line" >> $text
-    fi
+  elif [ "$inblock" == "1" ]; then
+    ## If in a backtick block, save the text to the temporary file
+    echo "$line" >> $text
   fi
 done < $file
 
-if [ $inblock -eq "1" ]; then
+if [ "$inblock" == "1" ]; then
   echo UNCLOSED BACKTICK BLOCK
+  FAIL=1
 fi
 
 if [ $FAIL -eq "1" ] ; then 
