Checkpoint

diff --git a/docs/check-examples b/docs/check-examples
--- a/docs/check-examples
+++ b/docs/check-examples
@@ -9,6 +9,7 @@
 ##                   dafny, java, text, cli, ...)
 ##    -x <int>   -- <int> is an (non-negative) integer literal giving 
 ##                  a default exit code
+##    -m         -- compare against error messages in headings
 ## It expects a file to be in github markdown format.
 ##
 ## It extracts each block of text that is between lines bounded by a pair
@@ -31,6 +32,10 @@
 ## command given by an option is used; if there is no such option, an error
 ## message is issued.
 ##
+## In the description of behavior below, if -m has been given as an option
+## then the comparison of the output line containing 'Error' is against the
+## error message as recorded in the '##' heading just before the test
+##
 ## Commands (here $F is the name of a file containing the dafny source code
 ## under test):
 ##   %no-check : do nothing
@@ -48,8 +53,12 @@
 ##                  the output is just a success message
 ##              (2) if <expect> is non-empty. then the exit code is 2 and
 ##                  the actual output matches the content of the file <expect>
-##   %check-error
-##   check
+##   %check-translate <expect> : runs the command
+##              "dafny translate --useBaseNameForFileName $F" and checks
+##              (1) if <expect> is absent then the exit code is 0 and
+##                  the output is just a success message
+##              (2) if <expect> is non-empty. then the exit code is r32 and
+##                  the actual output matches the content of the file <expect>
 
 dir=$(dirname "${BASH_SOURCE[0]}")
 dafny="$dir/../Scripts/dafny"
@@ -57,12 +66,14 @@ dafny="$dir/../Scripts/dafny"
 defaultCommand=
 defaultExit=
 defaultLang=
+useHeadings=0
 
-while getopts 'd:x:l:' opt; do
+while getopts 'md:x:l:' opt; do
   case "$opt" in
     "d") defaultCommand="$OPTARG";;
     "x") defaultExit="$OPTARG";;
     "l") defaultLang="$OPTARG";;
+    "m") useHeadings=1
   esac
 done
 shift $(($OPTIND - 1))
@@ -84,8 +95,6 @@ n=0
 ## if inblock==1 we are in a ```-delimited block
 inblock=0
 
-command= 
-expect= 
 msg=
 checkingErrors=1
 ## Read and process each line of the file.  The file is input on stdin 
@@ -100,12 +109,12 @@ do
    && msg=`echo "$line" | sed -E -e 's/^##[ ]*//' -e 's/_[a-z]+_/.*/g'`
 
   ## Check for the marker
-  echo $line | grep -e '^```' > /dev/null
+  echo "$line" | grep -e '^[ ]*```' > /dev/null
   if [ "$?" == "0" ]; then
     ##echo FOUND BACKTICKS IN $n "$line"
     if [ "$inblock" == "0" ]; then
       ## get language
-      lang=`echo "$line" | sed -e 's/^\`\`\`[\`]*//' -e 's/[ ].*$//'`
+      lang=`echo "$line" | sed -e 's/^[ ]*\`\`\`[\`]*//' -e 's/[ ].*$//'`
       if [ -z "$lang" ]; then
         lang=$defaultLang
         if [ -z "$lang" ]; then
@@ -114,12 +123,26 @@ do
         fi
       fi
 
+      action=
+      use=
       command=
       expect=
+      options=
       ( echo "$line" | grep -e '<!--' > /dev/null ) \
           && action=( `echo "$line" | sed -e 's/[^<]*<!--//' -e 's/-->//'` ) \
           && command=${action[0]} && expect=${action[1]}
-      if [ "lang" == "dafny" -a -z "$command" ]; then
+      ( echo "$line" | grep -e '%options' > /dev/null ) \
+          && options=( `echo "$line" | sed -e 's/^.*%options//' -e 's/-->//'` )
+      if [ "$expect" == "%use" -o "$expect" == "%options" ]; then
+        expect=
+      fi
+      if [ "${action[1]}" == "%use" ]; then
+        use=${action[2]}
+      fi
+      if [ "${action[2]}" == "%use" ]; then
+        use=${action[3]}
+      fi
+      if [ -z "$command" ]; then
         command="$defaultCommand"
         if [ -z "$command" ]; then
           echo "NO COMMAND GIVEN $n $line"
@@ -133,12 +156,24 @@ do
     else
       ## End of backtick block, so check the text
       inblock=0
+      if [ -n "$use" ]; then
+        ##echo " " USING $use
+        cat "$use" >> $text
+      fi
+      echo $line | grep '%save' > /dev/null
+      if [ "$?" == "0" ]; then
+         rest=( `echo $line | sed -e 's/^[^%]*%save//'` )
+         save=${rest[0]}
+         ##echo " SAVING" $save
+         cp $text $save
+      fi
       if [ "$lang" == "dafny" -o "$lang" == "cli" ]; then
-        echo TESTING $n $file $command $expect
+        echo TESTING $n $file "$command" $expect
       fi
       if [ "$command" == "%no-check" ]; then
         echo -n ""
-      elif [ "$command" == "%check-verify" -o "$command" == "%check-verify-warn" -o "$command" == "%check-resolve" ]; then
+      elif [ "$command" == "%check-verify" -o "$command" == "%check-verify-warn" -o "$command" == "%check-resolve"  -o "$command" == "%check-run" -o "$command" == "%check-translate" ]; then
+        capture=1
         if [ "$command" == "%check-verify" ]; then
           com=verify
           ec=4
@@ -148,14 +183,36 @@ do
         elif [ "$command" == "%check-resolve" ]; then
           com=resolve
           ec=2
+        elif [ "$command" == "%check-translate" ]; then
+          com=translate
+          ec=3
+        elif [ "$command" == "%check-run" ]; then
+          com=run
+          ec=0
         fi
         if [ "$lang" != "dafny" ]; then
           echo EXPECTED A dafny BLOCK, NOT $lang
           FAIL=1
         else
-          "$dafny" $com --useBaseNameForFileName $text > actual
+          if [ "$capture" == "2" ]; then
+            "$dafny" $com --useBaseNameForFileName $options $text 2> actual > /dev/null
+          else
+            "$dafny" $com --useBaseNameForFileName $options $text > actual
+          fi
           actualec=$?
-          if [ -z "$expect" ]; then
+          if [ "$useHeadings" == "1" ]; then
+            if [ "$actualec" != "$ec" ]; then
+              echo EXPECTED EXIT CODE $ec, got $actualec
+              FAIL=1
+            fi
+            act=`cat actual | grep Error | sed -e 's/^[^:]*: //'`
+            dif=`echo $act | sed -e "s/$msg//"`
+            if [ -n "$dif" ] ; then
+               echo NO MATCH "$msg" VS "$act"
+               FAIL=1
+            fi
+            msg=
+          elif [ -z "$expect" ]; then
             if [ "$actualec" != "0" ]; then
               echo "TEST FAILED" $file line $n  $command $expect
               cat $text
@@ -189,11 +246,11 @@ do
           fi
         fi
       elif [ "$command" == "%check-cli" ]; then
-        if [ "$lang" != "dafny" ]; then
-          echo EXPECTED A cli BLOCK, NOT $lang
+        if [ "$lang" != "bash" ]; then
+          echo EXPECTED A bash BLOCK, NOT $lang
           FAIL=1
         else
-          bash $command
+          . $text > actual
           ec=$?
           if [ "$ec" != "1" ]; then
              echo EXPECTED EXIT CODE OF 1, GOT $ec
@@ -207,15 +264,6 @@ do
             fi
           fi
         fi
-      elif [ "$command" == "%check-error" ]; then
-        "$dafny" resolve -useBaseNameForFileName $text | head -1 | sed -e 's/[^:]*: //' > actual
-        act=`cat actual`
-	dif=`echo $act | sed -e "s/$msg//"`
-        if [ -n "$dif" ] ; then
-           echo NO MATCH "$msg" VS "$act"
-           FAIL=1
-        fi
-        msg=
       elif [ "$lang" == "dafny" ]; then
          echo UNKNOWN TEST COMMAND $command
          FAIL=1
@@ -223,7 +271,7 @@ do
     fi
   elif [ "$inblock" == "1" ]; then
     ## If in a backtick block, save the text to the temporary file
-    echo "$line" | sed -e 's/\.\.\./   /' >> $text
+    echo "$line" | sed -e 's/[ ]*\.\.\./   /' >> $text
   fi
 done < $file
 
@@ -237,6 +285,6 @@ if [ $FAIL -eq "1" ] ; then
   ANYFAIL=1
 fi
 
+rm -f actual $text *.tmp
 done
-rm -f actual $text
 exit $ANYFAIL
