Further development

diff --git a/docs/check-examples b/docs/check-examples
--- a/docs/check-examples
+++ b/docs/check-examples
@@ -45,6 +45,15 @@ do
           cat actual
           FAIL=1
         fi
+        if [ -n "$expect" ]; then
+            diff actual $expect
+            if "$?" -ne "0" ]; then
+                FAIL=1
+                echo Actual output differs from expected
+                echo "TEST FAILED" $file line $n  $command $expect
+                cat $text
+            fi
+        fi
       else
          echo UNKNOWN TEST COMMAND $command
       fi
