Edits to guide.md

diff --git a/docs/check-examples b/docs/check-examples
--- a/docs/check-examples
+++ b/docs/check-examples
@@ -34,17 +34,19 @@
 ## Commands (here $F is the name of a file containing the dafny source code
 ## under test):
 ##   %no-check : do nothing
-##   %check-verify <expect> : runs the command 
+##   %check-verify <expect> or
+##   %check-verify-warn : runs the command 
 ##              "dafny verify --useBaseNameForFileName $F" and checks 
 ##              (1) if <expect> is absent then the exit code is 0 and
 ##                  the output is just a success message
-##              (2) if <exp[ect> is non-empty. then the exit code is 4 and
+##              (2) if <expect> is non-empty. then the exit code is 4 and
 ##                  the actual output matches the content of the file <expect>
+##                  if the command is %check-verify-warn, the exit code is 0
 ##   %check-resolve <expect> : runs the command
 ##              "dafny resolve --useBaseNameForFileName $F" and checks
 ##              (1) if <expect> is absent then the exit code is 0 and
 ##                  the output is just a success message
-##              (2) if <exp[ect> is non-empty. then the exit code is 2 and
+##              (2) if <expect> is non-empty. then the exit code is 2 and
 ##                  the actual output matches the content of the file <expect>
 ##   %check-error
 ##   check
@@ -132,15 +134,25 @@ do
       echo TESTING $n $file $command $expect
       if [ "$command" == "%no-check" ]; then
         echo -n ""
-      elif [ "$command" == "%check-verify" ]; then
+      elif [ "$command" == "%check-verify" -o "$command" == "%check-verify-warn" -o "$command" == "%check-resolve" ]; then
+        if [ "$command" == "%check-verify" ]; then
+          com=verify
+          ec=4
+        elif [ "$command" == "%check-verify-warn" ]; then
+          com=verify
+          ec=0
+        elif [ "$command" == "%check-resolve" ]; then
+          com=resolve
+          ec=2
+        fi
         if [ "$lang" != "dafny" ]; then
           echo EXPECTED A dafny BLOCK, NOT $lang
           FAIL=1
         else
-          "$dafny" verify --useBaseNameForFileName $text > actual
-          ec=$?
+          "$dafny" $com --useBaseNameForFileName $text > actual
+          actualec=$?
           if [ -z "$expect" ]; then
-            if [ "$ec" != "0" ]; then
+            if [ "$actualec" != "0" ]; then
               echo "TEST FAILED" $file line $n  $command $expect
               cat $text
               cat actual
@@ -152,8 +164,8 @@ do
               FAIL=1
             fi
           else
-            if [ "$ec" != "4" ]; then
-              echo EXPECTED EXIT CODE 4, got $ec
+            if [ "$actualec" != "$ec" ]; then
+              echo EXPECTED EXIT CODE $ec, got $actualec
               FAIL=1
             fi
             if [ -e "$expect" ]; then
@@ -166,46 +178,6 @@ do
                 cat actual
               fi
             else
-              echo EXPECT FILE $expect DOES NOT EXIST
-              cat actual
-              FAIL=1
-            fi
-          fi
-        fi
-      elif [ "$command" == "%check-resolve" ]; then
-        if [ "$lang" != "dafny" ]; then
-          echo EXPECTED A dafny BLOCK, NOT $lang
-          FAIL=1
-        else
-          "$dafny" resolve --useBaseNameForFileName $text > actual
-          ec=$?
-          if [ -z "$expect" ]; then
-            if [ "$ec" != "0" ]; then
-              echo "TEST FAILED" $file line $n  $command $expect
-              cat $text
-              cat actual
-              FAIL=1
-            fi
-            if [ `cat actual | wc -l ` != "2" ]; then
-              echo ACTUAL ERROR OUTPUT BUT NONE EXPECTED
-              cat actual
-              FAIL=1
-            fi
-          else
-            if [ "$ec" != "2" ]; then
-              echo EXPECTED EXIT CODE 2, got $ec
-              FAIL=1
-            fi
-            if [ -e "$expect" ]; then
-              diff actual $expect
-              if [ "$?" -ne "0" ]; then
-                FAIL=1
-                echo Actual output differs from expected
-                echo "TEST FAILED" $file line $n  $command $expect
-                cat $text
-                cat actual
-              fi
-            else 
               echo EXPECT FILE $expect DOES NOT EXIST
               cat actual
               FAIL=1
