Checking errorids when checking examples

diff --git a/docs/check-examples b/docs/check-examples
--- a/docs/check-examples
+++ b/docs/check-examples
@@ -126,7 +126,8 @@ do
   ## May not be robust against parentheses, brackets or other regex-special symbols in the error message -- none of these encountered so far.
 
   ( echo "$line" | grep -E -e '[#][#] ' > /dev/null ) \
-   && msg=`echo "$line" | sed -E -e 's/ \{#.*\}[ ]*$//' -e 's/^##[ ]*[*]*//' -e 's/[*]*$//' -e 's/\\*/\\\\*/' -e 's/_[a-z]+_/.*/g'`
+   && msg=`echo "$line" | sed -E -e 's/ \{#.*\}[ ]*$//' -e 's/^##[ ]*[*]*//' -e 's/[*]*$//' -e 's/\\*/\\\\*/' -e 's/_[a-z]+_/.*/g'` \
+   && expid=`echo $line | sed -e 's/^.*[\{][\#]//' -e 's/[\}]$//'`
 
   ## Check for the test command information
   echo "$line" | grep '^[ ]*<!-- [ ]*%' > /dev/null
@@ -201,7 +202,7 @@ do
          save=
       fi
       if [ "$lang" == "dafny" -o "$lang" == "cli" ]; then
-        echo TESTING $n $file "$command" $expect
+        echo "TESTING $n $file $command $expect $expid"
       fi
       if [ "$command" == "%no-check" ]; then
         echo -n ""
@@ -269,11 +270,20 @@ do
           elif [ "$command" == "%check-legacy" ]; then
             "$dafny" $com $dOptions ${options[@]} $text  > actual
           else
-            "$dafny" $com --function-syntax:4 $dOptions ${options[@]} $text > actual
+            "$dafny" $com --function-syntax:4 --verbose $dOptions ${options[@]} $text > actual
           fi
           actualec=$?
           if [ "$useHeadings" == "1" ]; then
-            act=`cat actual | grep -E '(Error|Warning):' | sed -e 's/^[^:]*: //'`
+            cat actual | grep -E '(Error|Warning):' > actual_error
+            eid=
+            grep 'ID:' actual_error > /dev/null
+            if [ "$?" == "0" ]; then
+              eid=`cat actual_error | sed -e 's/^.*[\(]ID: //' -e 's/[\)]$//'`
+            fi
+            act=`cat actual_error | sed -e 's/^[^:]*: //' -e 's/ [ ]*[\(]ID: .*$//'`
+            if [ "$eid" != "$expid" ] ; then
+              echo ERROR ID MISMATCH "$eid : $expid"
+            fi
             if [ -n "$msg" ]; then
               dif=`echo $act | sed -e "s@$msg@@g" | sed -e 's/[ ]*//'`
               if [ -z "$act" ] ; then
