Partial progress

diff --git a/docs/check-examples b/docs/check-examples
--- a/docs/check-examples
+++ b/docs/check-examples
@@ -36,9 +36,16 @@
 ##   %no-check : do nothing
 ##   %check-verify <expect> : runs the command 
 ##              "dafny verify --useBaseNameForFileName $F" and checks 
-##              (1) that the exit code is 0
-##              (2) if <expect> is non-empty then it names a file whose
-##                  content matches the actrual output of the above command
+##              (1) if <expect> is absent then the exit code is 0 and
+##                  the output is just a success message
+##              (2) if <exp[ect> is non-empty. then the exit code is 4 and
+##                  the actual output matches the content of the file <expect>
+##   %check-resolve <expect> : runs the command
+##              "dafny resolve --useBaseNameForFileName $F" and checks
+##              (1) if <expect> is absent then the exit code is 0 and
+##                  the output is just a success message
+##              (2) if <exp[ect> is non-empty. then the exit code is 2 and
+##                  the actual output matches the content of the file <expect>
 ##   %check-error
 ##   check
 
@@ -148,6 +155,40 @@ do
           else
             if [ "$ec" != "4" ]; then
               echo EXPECTED EXIT CODE 4, got $ec
+              FAIL=1
+            fi
+            diff actual $expect
+            if [ "$?" -ne "0" ]; then
+              FAIL=1
+              echo Actual output differs from expected
+              echo "TEST FAILED" $file line $n  $command $expect
+              cat $text
+            fi
+          fi
+        fi
+      elif [ "$command" == "%check-resolve" ]; then
+        echo TESTING $n $file
+        if [ "$lang" != "dafny" ]; then
+          echo EXPECTED A dafny BLOCK, NOT $lang
+          FAIL=1
+        else
+          "$dafny" verify --useBaseNameForFileName $text > actual
+          ec=$?
+          if [ -z "$expect" ]; then
+            if [ "$ec" != "0" ]; then
+              echo "TEST FAILED" $file line $n  $command $expect
+              cat $text
+              cat actual
+              FAIL=1
+            fi
+            if [ `cat actual | wc -l ` != "2" ]; then
+              echo EXPECTED SUCCESS OUTPUT
+              cat actual
+              FAIL=1
+            fi
+          else
+            if [ "$ec" != "2" ]; then
+              echo EXPECTED EXIT CODE 2, got $ec
               FAIL=1
             fi
             diff actual $expect
