Update Z3 paths, replace /z3exe switch

diff --git a/.github/workflows/release-downloads.yml b/.github/workflows/release-downloads.yml
--- a/.github/workflows/release-downloads.yml
+++ b/.github/workflows/release-downloads.yml
@@ -72,18 +72,18 @@ jobs:
     - name: Check - non Windows
       if: runner.os != 'Windows'
       run: |
-        dafny/dafny /compileVerbose:0 /compile:0 a.dfy /z3exe:dafny/z3/bin/z3
+        dafny/dafny /compileVerbose:0 /compile:0 a.dfy /proverOpt:PROVER_PATH=dafny/z3/bin/z3
     - name: Check - Windows
       if: runner.os == 'Windows'
-      run: dafny/dafny /compileVerbose:0 /compile:0 a.dfy /z3exe:dafny/z3/bin/z3.exe
+      run: dafny/dafny /compileVerbose:0 /compile:0 a.dfy /proverOpt:PROVER_PATH=dafny/z3/bin/z3.exe
     - name: Check bad
       run: dafny/dafny /compile:0 b.dfy || echo "EXPECTED FAILURE" ; exit 0
     - name: Check bad - non Windows
       if: runner.os != 'Windows'
-      run: dafny/dafny /compile:0 b.dfy /z3exe:dafny/z3/bin/z3 || echo "EXPECTED FAILURE"
+      run: dafny/dafny /compile:0 b.dfy /proverOpt:PROVER_PATH=dafny/z3/bin/z3 || echo "EXPECTED FAILURE"
     - name: Check bad - Windows
       if: runner.os == 'Windows'
-      run: (dafny/Dafny.exe /compile:0 b.dfy /z3exe:dafny/z3/bin/z3.exe || echo "EXPECTED FAILURE") ; exit 0
+      run: (dafny/Dafny.exe /compile:0 b.dfy /proverOpt:PROVER_PATH=dafny/z3/bin/z3.exe || echo "EXPECTED FAILURE") ; exit 0
     ## Check that a simple program compiles and runs on each supported platform
     - name: Check C# compile
       run: |
