Using new CLI in smoke tests

diff --git a/.github/workflows/release-downloads.yml b/.github/workflows/release-downloads.yml
--- a/.github/workflows/release-downloads.yml
+++ b/.github/workflows/release-downloads.yml
@@ -70,37 +70,29 @@ jobs:
         dafny/z3/bin/z3-4.12.1 -version
         dafny/dafny -version
     - name: Check
-      run: dafny/dafny /compileVerbose:0 /compile:0 a.dfy
-    - name: Check - non Windows
-      if: runner.os != 'Windows'
-      run: |
-        dafny/dafny /compileVerbose:0 /compile:0 a.dfy
-    - name: Check - Windows
-      if: runner.os == 'Windows'
-      run: dafny/dafny /compileVerbose:0 /compile:0 a.dfy
-    - name: Check bad
-      run: dafny/dafny /compile:0 b.dfy || echo "EXPECTED FAILURE" ; exit 0
+      run: dafny/dafny verify a.dfy
     - name: Check bad - non Windows
       if: runner.os != 'Windows'
-      run: dafny/dafny /compile:0 b.dfy || echo "EXPECTED FAILURE"
+      run: dafny/dafny verify b.dfy || echo "EXPECTED FAILURE"
     - name: Check bad - Windows
       if: runner.os == 'Windows'
       run: (dafny/Dafny.exe /compile:0 b.dfy || echo "EXPECTED FAILURE") ; exit 0
     ## Check that a simple program compiles and runs on each supported platform
-    - name: run quicktests
-      run: |
-        npm install bignumber.js
-        dafny/quicktest.sh > log.txt
-        diff log.txt dafny/quicktest.out
     - name: Check C# compile
       run: |
-        dafny/dafny /compileVerbose:0 /compile:3 /compileTarget:cs /spillTargetCode:3 a.dfy
+        dafny/dafny run -t:cs a.dfy > actual.txt
+        diff expect.txt actual.txt
+        dafny/dafny build -t:cs a.dfy
+        dotnet a.dll > actual.txt
+        diff expect.txt actual.txt
     - name: Check Go compile
       run: |
-        dafny/dafny /compile:3 /spillTargetCode:3 /compileTarget:go a.dfy
+        dafny/dafny run -t:go a.dfy > actual.txt
+        diff expect.txt actual.txt
     - name: Running Go artifacts
       if: runner.os != 'Windows'
       run: |
+        dafny/dafny build -t:go a.dfy
         GO111MODULE=auto GOPATH=$PWD/a-go go run a-go/src/a.go > actual.txt
         diff expect.txt actual.txt
     - name: Running Go artifacts - Windows
@@ -113,20 +105,31 @@ jobs:
         diff expect.txt actual.txt
     - name: Check Javascript compile
       run: |
-        dafny/dafny /compile:3 /spillTargetCode:3 /compileTarget:js a.dfy
+        dafny/dafny run -t:js a.dfy > actual.txt
+        diff expect.txt actual.txt
+        dafny/dafny build -t:js a.dfy
         node a.js dafny/DafnyRuntime.js > actual.txt
         diff expect.txt actual.txt
     - name: Check Java compile
       run: |
         (ls dafny/DafnyRuntime.jar || echo NO DafnyRuntime.jar )
-        dafny/dafny /compile:3 /spillTargetCode:3 /compileTarget:java a.dfy
-    - name: Check Java artifacts
-      if: runner.os != 'Windows'
-      run: |
-        java -cp a-java:dafny/DafnyRuntime.jar a > actual.txt
+        dafny/dafny run -t:java a.dfy > actual.txt
         diff expect.txt actual.txt
-    - name: Check Java artifacts - Windows
-      if: runner.os == 'Windows'
-      run: |
-        java -cp "a-java;dafny/DafnyRuntime.jar" a > actual.txt
+        dafny/dafny build -t:java a.dfy
+        java -jar a.jar > actual.txt
         diff expect.txt actual.txt
+    - name: Check Python compile
+      run: |
+        dafny/dafny run -t:py a.dfy > actual.txt
+        diff expect.txt actual.txt
+        dafny/dafny build -t:py a.dfy
+        python a.py > actual.txt
+        diff expect.txt actual.txt
+    ## quicktests.sh is a script for users to use to check that their
+    ## installation is OK. We run it here to be sure it works, even if
+    ## it duplicates some of the above.
+    - name: run quicktests
+      run: |
+        npm install bignumber.js
+        dafny/quicktest.sh > log.txt
+        diff log.txt dafny/quicktest.out
