Use `dafny/dafny` -> `dafny` for NuGet test

diff --git a/.github/workflows/release-downloads-nuget.yml b/.github/workflows/release-downloads-nuget.yml
--- a/.github/workflows/release-downloads-nuget.yml
+++ b/.github/workflows/release-downloads-nuget.yml
@@ -70,29 +70,29 @@ jobs:
         z3 -version
         dafny -version
     - name: Check
-      run: dafny/dafny /compileVerbose:0 /compile:0 a.dfy
+      run: dafny /compileVerbose:0 /compile:0 a.dfy
     - name: Check - non Windows
       if: runner.os != 'Windows'
       run: |
-        dafny/dafny /compileVerbose:0 /compile:0 a.dfy
+        dafny /compileVerbose:0 /compile:0 a.dfy
     - name: Check - Windows
       if: runner.os == 'Windows'
-      run: dafny/dafny /compileVerbose:0 /compile:0 a.dfy
+      run: dafny /compileVerbose:0 /compile:0 a.dfy
     - name: Check bad
-      run: dafny/dafny /compile:0 b.dfy || echo "EXPECTED FAILURE" ; exit 0
+      run: dafny /compile:0 b.dfy || echo "EXPECTED FAILURE" ; exit 0
     - name: Check bad - non Windows
       if: runner.os != 'Windows'
-      run: dafny/dafny /compile:0 b.dfy || echo "EXPECTED FAILURE"
+      run: dafny /compile:0 b.dfy || echo "EXPECTED FAILURE"
     - name: Check bad - Windows
       if: runner.os == 'Windows'
       run: (dafny/Dafny.exe /compile:0 b.dfy || echo "EXPECTED FAILURE") ; exit 0
     ## Check that a simple program compiles and runs on each supported platform
     - name: Check C# compile
       run: |
-        dafny/dafny /compileVerbose:0 /compile:3 /compileTarget:cs /spillTargetCode:3 a.dfy
+        dafny /compileVerbose:0 /compile:3 /compileTarget:cs /spillTargetCode:3 a.dfy
     - name: Check Go compile
       run: |
-        dafny/dafny /compile:3 /spillTargetCode:3 /compileTarget:go a.dfy
+        dafny /compile:3 /spillTargetCode:3 /compileTarget:go a.dfy
     - name: Running Go artifacts
       if: runner.os != 'Windows'
       run: |
@@ -109,9 +109,9 @@ jobs:
     - name: Check Javascript compile
       run: |
         npm install bignumber.js
-        dafny/dafny /compile:3 /spillTargetCode:3 /compileTarget:js a.dfy
+        dafny /compile:3 /spillTargetCode:3 /compileTarget:js a.dfy
         node a.js dafny/DafnyRuntime.js > actual.txt
         diff expect.txt actual.txt
     - name: Check Java compile
       run: |
-        dafny/dafny /compile:3 /spillTargetCode:3 /compileTarget:java a.dfy
+        dafny /compile:3 /spillTargetCode:3 /compileTarget:java a.dfy
