Fixing scripts - 64

diff --git a/.github/workflows/release-downloads.yml b/.github/workflows/release-downloads.yml
--- a/.github/workflows/release-downloads.yml
+++ b/.github/workflows/release-downloads.yml
@@ -86,13 +86,13 @@ jobs:
       if: runner.os == 'Windows'
       run: dafny/dafny /compileVerbose:0 /compile:0 a.dfy /z3exe:z3/bin/z3.exe
     - name: Check bad
-      run: dafny/dafny /compile:0 b.dfy || echo "EXPECTED FAILURE"
+      run: dafny/dafny /compile:0 b.dfy || echo "EXPECTED FAILURE" ; exit 0
     - name: Check bad - non Windows
       if: runner.os != 'Windows'
-      run: dafny/dafny /compile:0 b.dfy /z3exe:z3/bin/z3 || echo "EXPECTED FAILURE"; exit 0
+      run: dafny/dafny /compile:0 b.dfy /z3exe:z3/bin/z3 || echo "EXPECTED FAILURE"
     - name: Check bad - Windows
       if: runner.os == 'Windows'
-      run: dafny/dafny /compile:0 b.dfy /z3exe:z3/bin/z3i.exe || echo "EXPECTED FAILURE"; exit 0
+      run: (dafny/dafny /compile:0 b.dfy /z3exe:z3/bin/z3.exe || echo "EXPECTED FAILURE") && exit 0
     ## Check that a simple program compiles and runs on each supported platform
     - name: Check C# compile
       run: |
