Making dafny an input

diff --git a/.github/workflows/reusable-smoke-test.yml b/.github/workflows/reusable-smoke-test.yml
--- a/.github/workflows/reusable-smoke-test.yml
+++ b/.github/workflows/reusable-smoke-test.yml
@@ -6,6 +6,10 @@ on:
       os:
         required: true
         type: string
+      dafnyexe:
+        required: true
+        type: string
+
 jobs:
   smoke-test:
     runs-on: ${{ inputs.os }}
@@ -13,7 +17,7 @@ jobs:
     steps:
     - name: Versions
       run: |
-        dafny/dafny --version
+        ${{ inputs.dafnyexe }} --version
         # -version is not supported in old dafny,
         # but this gives the version with an error
         dotnet --list-sdks
@@ -28,58 +32,57 @@ jobs:
 
     ## Check that dafny and z3 run and that a simple program verifies or fails
     - name: Check
-      run: dafny/dafny verify a.dfy
+      run: ${{ inputs.dafnyexe }} verify a.dfy
     - name: Check bad - non Windows
       if: runner.os != 'Windows'
-      run: dafny/dafny verify b.dfy || echo "EXPECTED FAILURE"
+      run: ${{ inputs.dafnyexe }} verify b.dfy || echo "EXPECTED FAILURE"
     - name: Check bad - Windows
       if: runner.os == 'Windows'
       run: (dafny/Dafny.exe verify b.dfy || echo "EXPECTED FAILURE") ; exit 0
     ## Check that a simple program compiles and runs on each supported platform
     - name: Check C# compile
       run: |
-        dafny/dafny run -t:cs a.dfy > actual.txt
+        ${{ inputs.dafnyexe }} run -t:cs a.dfy > actual.txt
         diff expect.txt actual.txt
-        dafny/dafny build -t:cs a.dfy
+        ${{ inputs.dafnyexe }} build -t:cs a.dfy
         dotnet a.dll > actual.txt
         diff expect.txt actual.txt
     - name: Check Go compile
       run: |
-        dafny/dafny run -t:go a.dfy > actual.txt
+        ${{ inputs.dafnyexe }} run -t:go a.dfy > actual.txt
         diff expect.txt actual.txt
     - name: Running Go artifacts
       if: runner.os != 'Windows'
       run: |
-        dafny/dafny build -t:go a.dfy
+        ${{ inputs.dafnyexe }} build -t:go a.dfy
         GO111MODULE=auto GOPATH=$PWD/a-go go run a-go/src/a.go > actual.txt
         diff expect.txt actual.txt
     - name: Running Go artifacts - Windows
       shell: pwsh
       if: runner.os == 'Windows'
       run: |
-        dafny/dafny build -t:go a.dfy
+        ${{ inputs.dafnyexe }} build -t:go a.dfy
         $Env:GO111MODULE="auto"
         $Env:GOPATH="$PWD/a-go"
         go run a-go/src/a.go > actual.txt
         diff expect.txt actual.txt
     - name: Check Javascript compile
       run: |
-        dafny/dafny run -t:js a.dfy > actual.txt
+        ${{ inputs.dafnyexe }} run -t:js a.dfy > actual.txt
         diff expect.txt actual.txt
-        dafny/dafny build -t:js a.dfy
+        ${{ inputs.dafnyexe }} build -t:js a.dfy
         node a.js dafny/DafnyRuntime.js > actual.txt
         diff expect.txt actual.txt
     - name: Check Java compile
       run: |
-        (ls dafny/DafnyRuntime.jar || echo NO DafnyRuntime.jar )
-        dafny/dafny run -t:java a.dfy > actual.txt
+        ${{ inputs.dafnyexe }} -t:java a.dfy > actual.txt
         diff expect.txt actual.txt
-        dafny/dafny build -t:java a.dfy
+        ${{ inputs.dafnyexe }} build -t:java a.dfy
         java -jar a.jar > actual.txt
         diff expect.txt actual.txt
     - name: Check Python compile
       run: |
-        dafny/dafny run -t:py a.dfy > actual.txt
+        ${{ inputs.dafnyexe }} run -t:py a.dfy > actual.txt
         diff expect.txt actual.txt
-        dafny/dafny build -t:py a.dfy
+        ${{ inputs.dafnyexe }} build -t:py a.dfy
         python a.py > actual.txt
