Reusing the workflow in release-downloads

diff --git a/.github/workflows/reusable-smoke-test.yml b/.github/workflows/reusable-smoke-test.yml
--- a/.github/workflows/reusable-smoke-test.yml
+++ b/.github/workflows/reusable-smoke-test.yml
@@ -12,7 +12,12 @@ jobs:
     steps:
     - name: Versions
       run: |
-        dafny -version
+        pwd
+        ls
+        dafny/z3/bin/z3-4.8.5 -version
+        dafny/z3/bin/z3-4.12.1 -version
+        dafny/dafny -version
+        dafny --version
         which dafny
         # -version is not supported in old dafny,
         # but this gives the version with an error
@@ -25,28 +30,61 @@ jobs:
         echo "method Main() { assert true; print 42, '\n'; }" > a.dfy
         echo "method m() { assert false; }" > b.dfy
         echo "42" > expect.txt
+
+    ## Check that dafny and z3 run and that a simple program verifies or fails
     - name: Check
-      run: dafny verify a.dfy
-    - name: Check bad
-      run: dafny verify b.dfy || echo EXPECTED FAILURE
+      run: dafny/dafny verify a.dfy
+    - name: Check bad - non Windows
+      if: runner.os != 'Windows'
+      run: dafny/dafny verify b.dfy || echo "EXPECTED FAILURE"
+    - name: Check bad - Windows
+      if: runner.os == 'Windows'
+      run: (dafny/Dafny.exe verify b.dfy || echo "EXPECTED FAILURE") ; exit 0
     ## Check that a simple program compiles and runs on each supported platform
     - name: Check C# compile
       run: |
-        dafny /compileVerbose:0 /compile:3 /compileTarget:cs /spillTargetCode:3 a.dfy
+        dafny/dafny run -t:cs a.dfy > actual.txt
+        diff expect.txt actual.txt
+        dafny/dafny build -t:cs a.dfy
+        dotnet a.dll > actual.txt
+        diff expect.txt actual.txt
     - name: Check Go compile
       run: |
-        dafny build -t:go a.dfy
-        env GO111MODULE=auto GOPATH=$PWD/a-go go run a-go/src/a.go > actual.txt
+        dafny/dafny run -t:go a.dfy > actual.txt
+        diff expect.txt actual.txt
+    - name: Running Go artifacts
+      if: runner.os != 'Windows'
+      run: |
+        dafny/dafny build -t:go a.dfy
+        GO111MODULE=auto GOPATH=$PWD/a-go go run a-go/src/a.go > actual.txt
+        diff expect.txt actual.txt
+    - name: Running Go artifacts - Windows
+      shell: pwsh
+      if: runner.os == 'Windows'
+      run: |
+        dafny/dafny build -t:go a.dfy
+        $Env:GO111MODULE="auto"
+        $Env:GOPATH="$PWD/a-go"
+        go run a-go/src/a.go > actual.txt
         diff expect.txt actual.txt
     - name: Check Javascript compile
       run: |
-        npm install bignumber.js
-        dafny build -t:js a.dfy
+        dafny/dafny run -t:js a.dfy > actual.txt
+        diff expect.txt actual.txt
+        dafny/dafny build -t:js a.dfy
         node a.js dafny/DafnyRuntime.js > actual.txt
         diff expect.txt actual.txt
     - name: Check Java compile
       run: |
         (ls dafny/DafnyRuntime.jar || echo NO DafnyRuntime.jar )
-        #dafny /compile:3 /spillTargetCode:3 /compileTarget:java a.dfy
-        #java -cp a:dafny/DafnyRuntime.jar a > actual.txt
-        #diff expect.txt actual.txt
+        dafny/dafny run -t:java a.dfy > actual.txt
+        diff expect.txt actual.txt
+        dafny/dafny build -t:java a.dfy
+        java -jar a.jar > actual.txt
+        diff expect.txt actual.txt
+    - name: Check Python compile
+      run: |
+        dafny/dafny run -t:py a.dfy > actual.txt
+        diff expect.txt actual.txt
+        dafny/dafny build -t:py a.dfy
+        python a.py > actual.txt
